AdoptMascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pag.urls')), 
    path('solicitud/', include('solicitud.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pag/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from solicitud.views import GestionarSolicitudesView

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('update_password/', views.update_password, name='update_password'),
    path('mascota/<int:pk>', views.mascota, name='mascota'),
    path('tipo/<str:foo>', views.tipo, name='tipo'),
    path('tipo_summary/', views.tipo_summary, name='tipo_summary'),
    path('search/', views.search, name='search'),
    path('lista_mascotas/', views.lista_mascotas, name='lista_mascotas'),
    path('lista_lugares/', views.lista_lugares, name='lista_lugares'),
    path('gestionar-solicitudes/', GestionarSolicitudesView.as_view(), name='gestionar_solicitudes'),
    path('agregar_vacuna/', views.agregar_vacuna, name='agregar_vacuna'),
     path('agregar_vacuna_mascota/', views.agregar_vacuna_mascota, name='agregar_vacuna_mascota'),


    # CRUD de Mascotas
    path('tipo-mascota/nuevo/', views.crear_tipo_mascota, name='crear_tipo_mascota'),
    path('mascota/nueva/', views.crear_mascota, name='crear_mascota'),
    path('mascota/editar/<int:pk>/', views.editar_mascota, name='editar_mascota'),
    path('mascota/editar/', views.editar_mascota, name='buscar_mascota'),
    path('mascota/eliminar/<int:pk>/', views.eliminar_mascota, name='eliminar_mascota'),
    path('mascota/eliminar/', views.eliminar_mascota, name='buscar_mascota_eliminar'),


    # CRUD de Lugares de Adopción
    path('lugar/nuevo/', views.crear_lugar, name='crear_lugar'),
    path('lugar/editar/<int:pk>/', views.editar_lugar, name='editar_lugar'),
    path('lugar/editar/', views.editar_lugar, name='buscar_lugar'),
    path('lugar/eliminar/<int:pk>/', views.eliminar_lugar, name='eliminar_lugar'),
    path('lugar/eliminar/', views.eliminar_lugar, name='buscar_lugar_eliminar'),
]

pag/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Usuarios
class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    

# Perfil Completo Del Usuario
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username
    

# Crear Perfil De Usuario Por Defecto Cuando el Usuario Se Registra 
def create_profile(sender, instance, created, **kwargs):
	if created:
		user_profile = Profile(user=instance)
		user_profile.save()

# Automatizar Los Perfiles
post_save.connect(create_profile, sender=User)


# Negocios/locales/tiendas
class LugarAdopcion(models.Model):
    name = models.CharField(max_length=100)
    ubicacion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Lugares de Adopcion'


# Tipo/Especie de los animales
class Tipo(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'tipos'


class Mascota(models.Model):
    name = models.CharField(max_length=50)
    tamano = models.CharField(max_length=10)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, default=1)
    edad = models.CharField(max_length=10, default='', blank=True, null=False)
    sexo = models.CharField(max_length=10)
    descripcion = models.TextField(max_length=250, default='')
    lugar_adopcion = models.ForeignKey(LugarAdopcion, on_delete=models.CASCADE, null=False)
    image = models.ImageField(upload_to='uploads/mascota/')
    
    def __str__(self):
        return self.name
    

class Vacuna(models.Model):
    nombre_vacuna = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_vacuna


class MascotaVacuna(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    vacuna = models.ForeignKey(Vacuna, on_delete=models.CASCADE)
    fecha_aplicacion = models.DateTimeField()
    fecha_proxima = models.DateTimeField()

    def __str__(self):
        return f"{self.mascota.name} - {self.vacuna.nombre_vacuna}"

pag/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, UserInfoForm, UpdateUserForm, ChangePasswordForm, MascotaForm, LugarAdopcionForm, TipoMascotaForm, VacunaForm, MascotaVacunaForm
from .models import Mascota, Tipo, Profile, LugarAdopcion
from django.contrib.auth.models import User
from django.db.models import Q


# Crear nueva mascota
def crear_mascota(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Mascota creada exitosamente.')
            return redirect('home')
    else:
        form = MascotaForm()
    return render(request, 'formulario_mascota.html', {'form': form})

# Editar mascota existente
def editar_mascota(request, pk=None):
    mascota = None
    form = None

    # Si el usuario ha enviado un término de búsqueda por nombre
    query = request.GET.get('query')
    if query:
        mascotas = Mascota.objects.filter(name__icontains=query)
    else:
        mascotas = None

    # Si se recibe un pk específico para edición, cargar la mascota correspondiente
    if pk:
        mascota = get_object_or_404(Mascota, pk=pk)
        if request.method == 'POST':
            form = MascotaForm(request.POST, request.FILES, instance=mascota)
            if form.is_valid():
                form.save()
                messages.success(request, 'Mascota actualizada exitosamente.')
                return redirect('home')
        else:
            form = MascotaForm(instance=mascota)

    return render(request, 'editar_mascota.html', {
        'form': form,
        'mascota': mascota,
        'mascotas': mascotas,
        'query': query,
    })

# Eliminar mascota
def eliminar_mascota(request, pk=None):
    mascota = None

    # Si el usuario ha enviado un término de búsqueda por nombre
    query = request.GET.get('query')
    if query:
        mascotas = Mascota.objects.filter(name__icontains=query)
    else:
        mascotas = None

    # Si se recibe un pk específico, buscar la mascota para confirmar la eliminación
    if pk:
        mascota = get_object_or_404(Mascota, pk=pk)
        if request.method == 'POST':
            mascota.delete()
            messages.success(request, 'Mascota eliminada exitosamente.')
            return redirect('home')

    return render(request, 'eliminar_mascota.html', {
        'mascota': mascota,
        'mascotas': mascotas,
        'query': query,
    })

# Crear nuevo lugar de adopción
def crear_lugar(request):
    if request.method == 'POST':
        form = LugarAdopcionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Lugar de adopción creado exitosamente.')
            return redirect('home')
    else:
        form = LugarAdopcionForm()
    return render(request, 'formulario_lugar.html', {'form': form})

# Editar lugar de adopción existente
def editar_lugar(request, pk=None):
    lugar_adopcion = None
    form = None

    # Si el usuario ha enviado un término de búsqueda por nombre
    query = request.GET.get('query')
    if query:
        lugares = LugarAdopcion.objects.filter(name__icontains=query)
    else:
        lugares = None

    # Si se recibe un pk específico para edición, cargar el lugar correspondiente
    if pk:
        lugar_adopcion = get_object_or_404(LugarAdopcion, pk=pk)
        if request.method == 'POST':
            form = LugarAdopcionForm(request.POST, instance=lugar_adopcion)
            if form.is_valid():
                form.save()
                messages.success(request, 'Lugar de adopción actualizado exitosamente.')
                return redirect('home')  # Cambia 'home' por la URL a la que quieras redirigir
        else:
            form = LugarAdopcionForm(instance=lugar_adopcion)

    return render(request, 'editar_lugar.html', {
        'form': form,
        'lugar_adopcion': lugar_adopcion,
        'lugares': lugares,
        'query': query,
    })

# Eliminar lugar de adopción
def eliminar_lugar(request, pk=None):
    lugar_adopcion = None

    # Si el usuario ha enviado un término de búsqueda por nombre
    query = request.GET.get('query')
    if query:
        lugares = LugarAdopcion.objects.filter(name__icontains=query)
    else:
        lugares = None

    # Si se recibe un pk específico, buscar el lugar para confirmar la eliminación
    if pk:
        lugar_adopcion = get_object_or_404(LugarAdopcion, pk=pk)
        if request.method == 'POST':
            lugar_adopcion.delete()
            messages.success(request, 'Lugar de adopción eliminado exitosamente.')
            return redirect('home')  # Cambia 'home' por la URL adecuada para redirigir

    return render(request, 'eliminar_lugar.html', {
        'lugar_adopcion': lugar_adopcion,
        'lugares': lugares,
        'query': query,
    })


def crear_tipo_mascota(request):
    if request.method == 'POST':
        form = TipoMascotaForm(request.POST)  # Asegúrate de tener un formulario llamado TipoMascotaForm
        if form.is_valid():
            form.save()
            messages.success(request, 'Tipo de mascota creado exitosamente.')
            return redirect('home')  # Redirige a la página principal o a una lista de tipos de mascotas
    else:
        form = TipoMascotaForm()
    return render(request, 'formulario_tipo_mascota.html', {'form': form})


def home(request):
    return render(request, 'home.html', {})

def lista_lugares(request):
    lugares_adopcion = LugarAdopcion.objects.all() 
    return render(request, 'lista_lugares.html', {'lugares_adopcion': lugares_adopcion})

def lista_mascotas(request):
    mascotas = Mascota.objects.all()
    return render(request, 'lista_mascotas.html', {'mascotas':mascotas})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

            messages.success(request, ('Ha Iniciado Sesión'))
            return redirect('home')
        else:
            messages.success(request, ("Hubo Un Error, Inténtelo De Nuevo"))
            return redirect('login')
    else:
        return render(request, 'login.html', {})
    

def logout_user(request):
    logout(request)
    messages.success(request, ("Ha Cerrado La Sesión"))
    return redirect('home')
    

def register_user(request):
    form = SignUpForm
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Perfil Creado - Rellene Sus Datos De Usuario"))
            return redirect('home')
        else:
            messages.success(request, ("Hubo Un Error, Inténtelo De Nuevo"))
            return redirect('register')
    else:
        return render(request, 'register.html', {'form':form})
    

def tipo(request, foo):
    # reemplazar guiones con espacios
    foo = foo.replace('-', ' ')
    try:
        tipo = Tipo.objects.get(name=foo)
        mascotas = Mascota.objects.filter(tipo=tipo)
        return render(request, 'tipo.html', {'mascotas': mascotas, 'tipo': tipo})
    except:
        messages.success(request, ("Por ahora NO hay Mascotas de este Tipo"))
        return redirect('home')
    

def tipo_summary(request):
    tipos = Tipo.objects.all()  
    return render(request, 'tipo_summary.html', {'tipos':tipos})


def mascota(request, pk):
    mascota = Mascota.objects.get(id=pk)
    return render(request, 'mascota.html', {'mascota': mascota})


def update_info(request):
    if request.user.is_authenticated:
        # Obtener el Usuario Actual
        current_user = Profile.objects.get(user__id=request.user.id)
        # Formulario de Usuario
        form = UserInfoForm(request.POST or None, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(request, ("Su información ha sido actualizada"))
            return redirect('home') 
        return render(request, 'update_info.html', {'form':form})
    else:
        messages.success(request, "Debe iniciar sesión para acceder a esta página")
        return redirect('home')  
    

def update_user(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        user_form = UpdateUserForm(request.POST or None, instance=current_user)
        if user_form.is_valid():
            user_form.save()
            login(request, current_user)
            messages.success(request, ("Su Perfil Ha Sido Actualizado"))
            return redirect('home') 
        return render(request, 'update_user.html', {'user_form':user_form})
    else:
        messages.success(request, "Debe iniciar sesión para acceder a esta página")
        return redirect('home')
    

def update_password(request):
    if request.user.is_authenticated:
        current_user = request.user
        if request.method == 'POST':
            form = ChangePasswordForm(current_user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Su Contraseña ha sido actualizada")
                login(request, current_user)
                return redirect('home')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
        else:
            form = ChangePasswordForm(current_user) 
        return render(request, 'update_password.html', {'form':form})
    else:  

pag/templates/agregar_vacuna_mascota.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">Agregar Vacuna a Mascota</h1>
          <p class="lead fw-normal text-white-50 mb-0">Registra una vacuna aplicada a una mascota</p>
      </div>
  </div>
</header>

<!-- Formulario -->
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <br/><br/>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br/><br/>
                <div class="text-center">
                    <button type="submit" class="btn btn-success mx-2">Guardar</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary mx-2">Cancelar</a>
                </div>
            </form>

            <br/><br/><br/><br/>
        </div>
    </div>
</div>

{% endblock %}

pag/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Ecommerce</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />



        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    </head>
    <body>

        {% include 'navbar.html' %}

        {% if messages %}

            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

            {% endfor %}

        {% endif %}

        {% block content %}
        {% endblock %}

        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Aplicación Web para Adopción de Mascotas 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
       <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

pag/templates/editar_mascota.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Editar Mascota</h1>
            <p class="lead fw-normal text-white-50 mb-0">Busca y edita la info de la mascota</p>
        </div>
    </div>
</header>

<!-- Formulario de Búsqueda -->
<div class="container my-4" style="max-width: 600px; margin: 0 auto;">
    <form method="GET" action="{% url 'buscar_mascota' %}">
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Buscar por nombre de mascota" value="{{ query }}">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
</div>

<!-- Resultados de Búsqueda -->
{% if mascotas %}
    <div class="container my-4" style="max-width: 600px; margin: 0 auto;">
        <h3>Resultados de la Búsqueda:</h3>
        <ul class="list-group">
            {% for mascota in mascotas %}
                <li class="list-group-item">
                    <a href="{% url 'editar_mascota' pk=mascota.id %}">{{ mascota.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<!-- Formulario de Edición -->
{% if mascota %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Actualizar</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
{% endif %}
<br><br><br><br><br><br>
{% endblock %}

pag/templates/eliminar_lugar.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Eliminar Lugar de Adopción</h1>
            <p class="lead fw-normal text-white-50 mb-0">Busca y elimina un lugar de adopción de la base de datos</p>
        </div>
    </div>
</header>

<!-- Formulario de Búsqueda -->
<div class="container my-4" style="max-width: 600px; margin: 0 auto;">
    <form method="GET" action="{% url 'buscar_lugar_eliminar' %}">
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Buscar por nombre del lugar" value="{{ query }}">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
</div>

<!-- Resultados de Búsqueda -->
{% if lugares %}
    <div class="container my-4" style="max-width: 600px; margin: 0 auto;">
        <h3>Resultados de la Búsqueda:</h3>
        <ul class="list-group">
            {% for lugar in lugares %}
                <li class="list-group-item">
                    <a href="{% url 'eliminar_lugar' pk=lugar.id %}">{{ lugar.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<!-- Confirmación de Eliminación -->
{% if lugar_adopcion %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <h3>¿Estás seguro que deseas eliminar el lugar de adopción {{ lugar_adopcion.name }}?</h3>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
<br><br><br><br>
{% endif %}

{% endblock %}

pag/templates/eliminar_mascota.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Eliminar Mascota</h1>
            <p class="lead fw-normal text-white-50 mb-0">Busca y elimina una mascota de la base de datos</p>
        </div>
    </div>
</header>

<!-- Formulario de Búsqueda -->
<div class="container my-4" style="max-width: 600px; margin: 0 auto;">
    <form method="GET" action="{% url 'buscar_mascota_eliminar' %}">
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Buscar por nombre de mascota" value="{{ query }}">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
</div>

<!-- Resultados de Búsqueda -->
{% if mascotas %}
    <div class="container my-4" style="max-width: 600px; margin: 0 auto;">
        <h3>Resultados de la Búsqueda:</h3>
        <ul class="list-group">
            {% for mascota in mascotas %}
                <li class="list-group-item">
                    <a href="{% url 'eliminar_mascota' pk=mascota.id %}">{{ mascota.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<!-- Confirmación de Eliminación -->
{% if mascota %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <h3>¿Estás seguro que deseas eliminar a {{ mascota.name }}?</h3>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>
<br><br><br><br>
{% endif %}

{% endblock %}

pag/templates/formulario_lugar.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">Crear Lugar de Adopción</h1>
          <p class="lead fw-normal text-white-50 mb-0">Crea un nuevo lugar de Apodción</p>
      </div>
  </div>
</header>

<!-- Formulario -->
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <br/><br/>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br/><br/>
                <button type="submit" class="btn btn-success">Guardar</button>
                <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
            </form>

            <br/><br/><br/><br/>
        </div>
    </div>
</div>

{% endblock %}

pag/templates/formulario_tipo_mascota.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">Crear Tipo de Mascota</h1>
          <p class="lead fw-normal text-white-50 mb-0">Agrega un Nuevo Tipo de Mascota</p>
      </div>
  </div>
</header>

<!-- Formulario -->
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <br/><br/>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br/><br/>
                <div class="text-center">
                    <button type="submit" class="btn btn-success mx-2">Guardar</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary mx-2">Cancelar</a>
                </div>
            </form>

            <br/><br/><br/><br/>
        </div>
    </div>
</div>

{% endblock %}

pag/templates/lista_lugares.html
{% extends 'base.html' %}

{% block content%}

    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Lugares de Adopción</h1>
                
            </div>
        </div>
    </header>

    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5">
            <div class="text-center">
                <h2 class="fw-bold"></h2>
            </div>
            <div class="row mt-4">
                {% for lugar in lugares_adopcion %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <div class="card-body text-center">
                                <h5 class="card-title">{{ lugar.name }}</h5>
                                <p class="card-text">Ubicación: {{ lugar.ubicacion }}</p>
                                <p class="card-text">Teléfono: {{ lugar.telefono }}</p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <p class="text-center">No hay lugares de adopción registrados aún.</p>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

pag/templates/lista_mascotas.html
{% extends 'base.html' %}

{% block content%}

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Encuentre su Mascota Favorita</h1>
                    
                </div>
            </div>
        </header>
        
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                    {% for mascota in mascotas %}
                        
                        <div class="col mb-5">
                            <div class="card h-100">
                                
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ mascota.image.url }}" alt="..." />
                                <!-- Product details -->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ mascota.name }}</h5>
                                        <br>
                                        
                                        <strong>Años: </strong>{{ mascota.edad }}
                                        <br>
                                        <strong>Tamaño: </strong>{{ mascota.tamano }} 
                                        <br>

                                        <!--
                                        <strong>Vacunas: </strong>
                                        {% for mascota_vacuna in mascota.mascotavacuna_set.all %}
                                            {{ mascota_vacuna.vacuna.nombre_vacuna }} (Aplicada el: {{ mascota_vacuna.fecha_aplicacion|date:"Y-m-d" }})
                                            <br>
                                        {% empty %}
                                            No tiene vacunas registradas.
                                        {% endfor %}
                                        -->
                          
                                    </div>
                                </div>

                                

                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'mascota' mascota.id %}">Ver mascota</a></div>
                                </div>
                            </div>
                        </div>
                        
                    {% endfor %}
                    
            </div>
        </section>

{% endblock %}
        